version: '3'

services:
  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    env_file:
      - .env
    environment:
      - POSTGRES_USER=piana
      - POSTGRES_DB=messages
      - POSTGRES_PASSWORD
